// Package models contains the types for schema 'alpha'.
package models

// GENERATED BY XO. DO NOT EDIT.

import (
	"errors"
	"time"
)

// TempFile represents a row from 'alpha.temp_files'.
type TempFile struct {
	MessageID   string     `json:"message_id"`   // message_id
	FileName    string     `json:"file_name"`    // file_name
	TimeCreated *time.Time `json:"time_created"` // time_created

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the TempFile exists in the database.
func (tf *TempFile) Exists() bool {
	return tf._exists
}

// Deleted provides information if the TempFile has been deleted from the database.
func (tf *TempFile) Deleted() bool {
	return tf._deleted
}

// Insert inserts the TempFile to the database.
func (tf *TempFile) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if tf._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO alpha.temp_files (` +
		`file_name, time_created` +
		`) VALUES (` +
		`?, ?` +
		`)`

	// run query
	XOLog(sqlstr, tf.FileName, tf.TimeCreated)
	res, err := db.Exec(sqlstr, tf.FileName, tf.TimeCreated)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	tf.MessageID = string(id)
	tf._exists = true

	return nil
}

// Update updates the TempFile in the database.
func (tf *TempFile) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !tf._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if tf._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE alpha.temp_files SET ` +
		`file_name = ?, time_created = ?` +
		` WHERE message_id = ?`

	// run query
	XOLog(sqlstr, tf.FileName, tf.TimeCreated, tf.MessageID)
	_, err = db.Exec(sqlstr, tf.FileName, tf.TimeCreated, tf.MessageID)
	return err
}

// Save saves the TempFile to the database.
func (tf *TempFile) Save(db XODB) error {
	if tf.Exists() {
		return tf.Update(db)
	}

	return tf.Insert(db)
}

// Delete deletes the TempFile from the database.
func (tf *TempFile) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !tf._exists {
		return nil
	}

	// if deleted, bail
	if tf._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM alpha.temp_files WHERE message_id = ?`

	// run query
	XOLog(sqlstr, tf.MessageID)
	_, err = db.Exec(sqlstr, tf.MessageID)
	if err != nil {
		return err
	}

	// set deleted
	tf._deleted = true

	return nil
}

// TempFileByMessageID retrieves a row from 'alpha.temp_files' as a TempFile.
//
// Generated from index 'temp_files_message_id_pkey'.
func TempFileByMessageID(db XODB, messageID string) (*TempFile, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`message_id, file_name, time_created ` +
		`FROM alpha.temp_files ` +
		`WHERE message_id = ?`

	// run query
	XOLog(sqlstr, messageID)
	tf := TempFile{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, messageID).Scan(&tf.MessageID, &tf.FileName, &tf.TimeCreated)
	if err != nil {
		return nil, err
	}

	return &tf, nil
}
